import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service",
  description: "Shorlabs terms of service — the rules and guidelines for using our platform.",
  alternates: {
    canonical: "/terms-of-service",
  },
};

export default function TermsOfService() {
  return (
    <main className="min-h-screen pt-24 pb-16">
      <div className="mx-auto max-w-3xl px-6 lg:px-8">
        <div className="prose prose-gray dark:prose-invert max-w-none">
          <h1>Terms of Service</h1>
          <p className="lead">Last Updated: March 19, 2026</p>

          <p>
            Welcome to Shorlabs. These Terms of Service ("Terms") govern your use of the Shorlabs website, PaaS offering, and associated tools. By accessing or using our services, you agree to comply with and be bound by these Terms.
          </p>

          <h2>1. Description of Services</h2>
          <p>
            Shorlabs provides cloud infrastructure and orchestration tools that allow developers to connect GitHub repositories, build applications, and deploy frontend and backend environments instantly. Features include auto-scaling, structured logging, custom domain mapping, and flexible compute provisioning.
          </p>

          <h2>2. Account Responsibilities</h2>
          <p>
            You are responsible for maintaining the confidentiality of your account credentials (managed via Clerk) and the security of your GitHub tokens/connections. You agree to notify us immediately of any unauthorized use of your account. Shorlabs is not liable for any loss or damage arising from your failure to protect your account credentials.
          </p>

          <h2>3. Acceptable Use Policy (AUP)</h2>
          <p>You agree not to use Shorlabs for any of the following prohibited activities:</p>
          <ul>
            <li>Hosting or distributing illegal, infringing, or malicious content (e.g., malware, viruses).</li>
            <li>Engaging in unauthorized cryptocurrency mining activities on our infrastructure.</li>
            <li>Attempting to bypass, reverse engineer, or exploit our infrastructure, AWS environments, or billing limits.</li>
            <li>Sending unsolicited communications (spam) or engaging in phishing.</li>
            <li>Running applications that intentionally disproportionately consume network, CPU, or memory resources to stress or harm the platform (e.g., DDoS).</li>
          </ul>
          <p>Violation of this AUP may result in immediate suspension or termination of your account without notice.</p>

          <h2>4. Pricing, Billing, and Usage Limits</h2>
          <p>
            Shorlabs operates on a tier-based and "pay per request" usage model. We track your usage metrics (e.g., requests, bandwidth, build minutes). By using the service, you agree to pay the fees associated with your tier and any overages you incur. You are fully responsible for the traffic and usage generated by applications hosted on your custom domains and subdomains. Unpaid balances or severe limit breaches may lead to service interruption.
          </p>

          <h2>5. Intellectual Property</h2>
          <p>
            <strong>Your Content:</strong> You retain full ownership, intellectual property rights, and responsibility for the code, applications, and data you deploy to Shorlabs. You grant us a limited license specifically to host, build, and run your code on our platform exclusively to provide the service to you.
            <br /><br />
            <strong>Our Platform:</strong> Shorlabs retains all ownership rights, intellectual property, and copyright to the platform, build automation pipelines, dashboard, and custom router infrastructure.
          </p>

          <h2>6. Warranties and Disclaimers</h2>
          <p>
            Our services are provided on an "AS IS" and "AS AVAILABLE" basis. While we strive to ensure high uptime and deploy stability, Shorlabs disclaims all warranties, express or implied, including the implied warranties of merchantability, fitness for a particular purpose, and non-infringement. We do not guarantee perfectly uninterrupted, secure, or error-free service.
          </p>

          <h2>7. Limitation of Liability</h2>
          <p>
            To the maximum extent permitted by applicable law, Shorlabs shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including loss of profits, data, code, use, or goodwill, resulting from your access to, integration with, or inability to access the services. Our total liability shall not exceed the amount you paid us over the past twelve (12) months.
          </p>

          <h2>8. Termination</h2>
          <p>
            You may terminate your account at any time. Shorlabs reserves the right to suspend or terminate your access to the platform at any time, with or without cause, including for violations of these Terms. Upon termination, all configurations, code, and running isolated containers will be deleted permanently.
          </p>

          <h2>9. Contact and Changes to Terms</h2>
          <p>
            We may update these Terms periodically to reflect changes to our architecture or legal requirements. Continued use of Shorlabs after such changes constitutes acceptance of the new Terms. For questions, please contact terms@shorlabs.com.
          </p>
        </div>
      </div>
    </main>
  );
}
